Don't restart onedrive service unless necessary

diff --git a/bin/manual-onedrive-sync b/bin/manual-onedrive-sync
--- a/bin/manual-onedrive-sync
+++ b/bin/manual-onedrive-sync
@@ -1,4 +1,22 @@
 #!/bin/sh
+
+restart=true
+
+while getopts ":n" opt; do
+  case $opt in
+    n)
+      restart=false
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
+done
+
 systemctl --user stop onedrive.service
 onedrive --sync
-systemctl --user start onedrive.service
+
+if $restart; then
+  systemctl --user start onedrive.service
+fi
